"""add_operations

Revision ID: 644c3899fa3e
Revises: bc1ce0de3578
Create Date: 2026-03-28 22:21:45.140291

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '644c3899fa3e'
down_revision: str | Sequence[str] | None = 'bc1ce0de3578'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_templates',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('specific_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_logs',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['operation_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'date', name='uq_operation_log_template_date')
    )
    op.create_index('ix_operation_logs_date', 'operation_logs', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_operation_logs_date', table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_table('operation_templates')
    # ### end Alembic commands ###
